name: Publish new releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]
        env: [staging, production]
    environment: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: "Create .env.dev file"
        if: ${{ matrix.env == 'staging' }}
        run: |
          rm .env.*
          touch .env.staging
          echo "# GitHub actions secrets: https://github.com/michael-freling/chrome-extension-anime-spoiler-blocker/settings/environments/3359267164/edit" >> .env.staging
          echo "PLASMO_PUBLIC_EXTENSION_ID=$PLASMO_PUBLIC_EXTENSION_ID" >> .env.staging
          echo "CRX_PUBLIC_KEY=$CRX_PUBLIC_KEY" >> .env.staging
        env:
          PLASMO_PUBLIC_EXTENSION_ID: ${{ vars.PLASMO_PUBLIC_EXTENSION_ID }}
          CRX_PUBLIC_KEY: ${{ secrets.CRX_PUBLIC_KEY }}

      - name: Build
        run: pnpm plasmo build --tag=${{ matrix.env }} --target=${{ matrix.browser }}-mv3 --zip

      - uses: actions/upload-artifact@v4
        with:
          name: extension-${{ matrix.browser }}-${{ matrix.env }}
          path: build/${{ matrix.browser }}-mv3-${{ matrix.env }}.zip

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: extension-*
          path: build
          merge-multiple: true

      - run: ls -lRa build

      # Create a GitHub release from the dist and a tag
      # https://github.com/ncipollo/release-action
      # https://earthly.dev/blog/github-action-artifacts/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.zip"
          # Following fields are for debugging
          # allowUpdates: true
          # tag: "v0.1.1"

      # Submit a release into a web store
      # https://docs.plasmo.com/framework/workflows/submit
      # - name: Browser Platform Publish
      #   uses: PlasmoHQ/bpp@v3
      #   with:
      #     keys: ${{ secrets.BPP_KEYS }}
      #     chrome-file: "build/chrome-mv3-production.zip"
      #     # version-file: "src/manifest.json"
      #     verbose: true
